### ISSUE TITLE
Unbinarized p3ds

### ISSUE THREAD

**Issue by odizzzle** [deathlyrage/breakingpointmod#1]
Is it possible to get unbinarized p3ds so that some objects can be repathed and put in pbos?

**Comment by deathlyrage** [comment]
Most of the p3ds on this repo should be unbinarized, however not all of them can be. It depends on what you are asking for? Can you be more specific?

**Comment by odizzzle** [comment]
Most of the weapon files are binarized to me. Also when I try to download the git, for some reason all the p3ds are 1kb. Multiple people try along with me, even with forking, but you still have to download them 1by1 to get the full size.

**Comment by deathlyrage** [comment]
You need to be using GIT LFS
