### ISSUE TITLE
Vehicle Spawning Problems

### ISSUE THREAD

**Issue by deathlyrage** [deathlyrage/breakingpointmod#10]
Vehicles often spawn on top of each other and the spawning checks are inconsistent and cause various problems. Sometimes vehicles duplicate after restart and there are two of them spawn on top of each other and explode.

**Comment by MorphineBP** [comment]
An exemple of this issue : http://steamcommunity.com/sharedfiles/filedetails/?id=1165189608 (sc taken less than 1m post restart).
Usually the 2 vecs are immediately exploding.

In my experience, it's not a duplication, the vec at the top is different and most of the time a Vannad/Hunter.
