### ISSUE TITLE
APL-SA p3ds

### ISSUE THREAD

**Issue by AdamKadmon** [deathlyrage/breakingpointmod#102]
Hi, 

Is it possible to re-upload on workshop some objects (p3ds) under APL-SA, and use said objects on a community that is approved by BI-Monetization? (Reserved slots) ?

Thanks

**Comment by DonniePlays** [comment]
The content on this GitHub is licensed as APL-SA. See the description of the license below:

_Noncommercial - You may not use this material for any commercial purposes._

See the main GitHub page for the license info.
