### ISSUE TITLE
Chernarus bench almost blocking barack hallway.

### ISSUE THREAD

**Issue by D4n2021** [deathlyrage/breakingpointmod#116]
In this enterable building in the red circle, there is a bench standing in the hallway. https://i.postimg.cc/9QG0r8fZ/bench-Chernarus.jpg

**Comment by Dani3lNL** [comment]
*red area. (cannot edit my post for some reason)

**Comment by DonniePlays** [comment]
This object cannot be removed from the map. It does not have a classname. The good news, the entire airfield now has way more enterable buildings that you can loot. You can also step over this bench to enter the barracks, so that building is not totally lost.
