### ISSUE TITLE
Heli crashes with no loot spawning

### ISSUE THREAD

**Issue by MorphineBP** [deathlyrage/breakingpointmod#13]
Happening from time to time, not very often.  Seems to be random.

**Comment by nadal28** [comment]
Did you try leaving the place and coming back after few mins? Yesterday I was playing and every town I visited all houses were empty, but if I came back after a few mins the loot spawned

**Comment by MorphineBP** [comment]
Yes, It seems to work sometimes, you're right. Maybe there is a delay to consider/fix.

**Comment by DonniePlays** [comment]
This is not a bug. There are three heli crash loot tables. One has a 100% chance to spawn every time, the second has a 85% chance to spawn and the third has a 75% chance to spawn loot. This is how the loot spawning is written in the code.
