### ISSUE TITLE
Boats floating in the air post-restart

### ISSUE THREAD

**Issue by MorphineBP** [deathlyrage/breakingpointmod#15]
After restart, all boats are floating in the air (5-10m high) on their spawn.
To solve the bug ingame (boats falling) :
- getting close
- shooting on it

Confirmed on Stratis. I'm not sure if it's happening at 100% on other maps (likely so).

**Comment by Overdese** [comment]
On Altis boats flying too, also i saw ATV in the air in Maxwell Camp on Stratis

**Comment by ST6Daniel** [comment]
Also on Thirsk Winter.

**Comment by Th3Dilli** [comment]
in breakingpointmod/ModSource/breakingpoint_server/CfgVehicleSpawns.hpp are the spawn points for the boats, and the z cord is few meters in the air, was that intended? @deathlyrage 

exampl Altis { x , y , z }
			Boats[] = 
			{
				{13307.2,14432.4,6.12484},
				{12518.5,12840.5,5.87228},
				{12121.6,10002.7,7.38112},
				{9732.42,10233.1,4.6753},
				{3277.35,12828.3,7.89433},
				{4165.81,16406.7,5.14801},
				{16549.1,12291.9,11.3114},
				{21914.7,6048.88,8.88409},
				{22260.2,8651.46,12.8674},
				{27629.2,24486.7,8.35412},
				{23272,24126.5,9.89698},
				{20596.6,19556.4,7.33971},
				{21690.6,20797.5,8.44836},
				{17693.4,18231.9,8.20155},
				{16841.9,20546.7,13.2509},
				{9727.87,22419.9,6.44237},
				{3768.15,17225.8,11.0542},
				{3321.96,14030.4,8.92366},
				{3576.07,10981.6,11.9546}
			};

**Comment by MorphineBP** [comment]
Fixed on Hotfix #1 for the 0.1722 patch (Server version).
