### ISSUE TITLE
BP Wiki

### ISSUE THREAD

**Issue by nadal28** [deathlyrage/breakingpointmod#16]
Idk where to post this so... I post it here :P

BP Wiki !!

http://aragones.info/BPWIKI/

**Comment by SirYwell** [comment]
Yeah using github wiki would be a good solution.

**Comment by julian167** [comment]
I can help u with the wiki here, if u need help.

**Comment by nadal28** [comment]
@julian167 Good, take a look here http://aragones.info/BPWIKI/

**Comment by Teh-Dango** [comment]
Is this wiki a go or is it dead in the water? I would not mind to compile some initial documents for it. Appears the links here are all 404'd.

**Comment by MorphineBP** [comment]
The work has been done already : https://github.com/deathlyrage/breakingpointmod/wiki
You can continue it if you want, there is already pretty much everything.

**Comment by Teh-Dango** [comment]
Oh I see it now thanks!
