### ISSUE TITLE
Remington Model 700 - 7.62 not killing on headshot?

### ISSUE THREAD

**Issue by D4n2021** [deathlyrage/breakingpointmod#17]
There was an issue with 7.62 not killing upon headshot. Model 700 rifle. Then he finally died from my friend with an AK magazine unloaded into him. Can wee check the damage values for all 7.62 ammunition that fits in the Model 700 ?

**Comment by MorphineBP** [comment]
Not specific of this weapon. General damage calculation system is sometimes erratic. Arma 3 bug ? (Arma 3 bug means nothing can be done about it on our side, BIS related).

**Comment by MorphineBP** [comment]
You can delete.

**Comment by Th3Dilli** [comment]
@ST6Daniel pls close
