### ISSUE TITLE
"Super crates" not ALWAYS spawning at any of the locations.

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#18]
We checked them (huge sniper rifle spawn crates), sometimes it only spawns to one of the locations on cherna, sometimes on none of them. afaik super crates should spawn on ALL super crate locations in same round, not only on ONE or even NONE of those locations, right?

**Comment by MorphineBP** [comment]
Wrong assumptions. Game mechanic (like Stratis) means only 1 crate out of all locations, sometimes no crate at all.

**Comment by ST6Daniel** [comment]
Can they spawn delayed too? Like 30 minutes into the round?

**Comment by MorphineBP** [comment]
Why didn't you learned first about it, before posting (.......) ? You don't know obviously, so how can you be accurate on anything !
SC spawns like loot (implying only if somebody close), despawn like loot (timer), respawn again.
SC does not spawn at all locations, and sometimes at none. It's on purpose oc.

**Comment by ST6Daniel** [comment]
ok then I understand any player who gets to an "active" supercrate will instantly trigger it to spawn. Ok. Just asked a question from a friend which I also couldn't answer him. Thx for clearing this up.

**Comment by ST6Daniel** [comment]
This issue can be deleted once you read the reply, @MorphineBP

**Comment by Th3Dilli** [comment]
Pls close issue because it is not a issue @ST6Daniel

**Comment by ST6Daniel** [comment]
But maybe we can let it up to the server admin with a yes/no setting to set if a crate ALWAYS spawns at one of the spawns or sometimes not at all.

**Comment by Th3Dilli** [comment]
that is not a issue that would be an enhancemend and atm not relevant, server owners can already choose if they want it on/off or replaced by gosthotel loot

**Comment by ST6Daniel** [comment]
Seriously?? And players (until today) NEVER got to see what that server setting is set to? Do you know how often I (and others probably too) went to crate spawns to find out there's no create spawning at those locations? :P

**Comment by ST6Daniel** [comment]
I mean it would be good for the client to see what the setting is on

**Comment by Th3Dilli** [comment]
if server owners want to they will put it in the server name. could close this one now?
