### ISSUE TITLE
Fire station - wall - stuck glitch

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#19]
When on roof of fire station, then standing in the corner of the roof, then holstering the M21 white feather rifle, as soon as the animation finished, I was hovering on that position and could not move. My teammate saw me hanging in the air outside the wall. So I think I was stuck inside the collision model roof-wall...

**Comment by MorphineBP** [comment]
This building is known for several collision bug.  Arma 3 bug.

**Comment by ST6Daniel** [comment]
But we can edit that 3D model or not?

**Comment by Th3Dilli** [comment]
Arma 2 Buildings are buggy and the ones used in BP are old so until someone updates those files in BP we have to wait, for now pls close the issue @ST6Daniel
