### ISSUE TITLE
Server question

### ISSUE THREAD

**Issue by skiperh1n1** [deathlyrage/breakingpointmod#2]
Hello. In source update have not a DB structure, map and configs server structure. Its will be be? Thanks

**Comment by elixirhope** [comment]
I also hope that soon the server files will appear and it will be possible to include their servers ... please do it faster

**Comment by skiperh1n1** [comment]
@elixirhope I`w seen sources and have ideas for making server files but its enough for make finish realization.

**Comment by WURS5000** [comment]
I still have the old files (db shem, configs) from the private hive but i highly doubt they working together, @deathlyrage?!

**Comment by skiperh1n1** [comment]
@WURS5000 I`m try this its work 50-50, because mission not for BP and havent DB must search tabels in scripts functions

**Comment by deathlyrage** [comment]
Getting released today

**Comment by WURS5000** [comment]
btw.: what's the discord?

**Comment by skiperh1n1** [comment]
@deathlyrage And where? :D

**Comment by deathlyrage** [comment]
https://discord.gg/0bdlQWbX7hbk40Yo
