### ISSUE TITLE
When leaving server browser (Esc key) these error messages appear

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#20]
You cannot play/edit this mission;

it is dependent on downloadable content that has been deleted.

cacharacters,
ca_animals2_rabbit,
CAWheeled3_TT650,
cacharacters2,
ca_missions_garbagecollector,
ca_modules_functions,
ca_animals2_wildboar,
ca_animals2_dogs_pastor,
ca_animals2_chicken,
ca_animals2_cow,
CAWheeled,
ca_animals2_sheep

**Comment by MorphineBP** [comment]
I don't have it. Looks like specific to OP mods folder/files.

**Comment by ST6Daniel** [comment]
Maybe only happening after having spawned on a server? U tried that?

**Comment by MorphineBP** [comment]
Yes I spawned like you a lot. You can delete, it's not a BP bug.
You can also forget all things related to windows spawning on your screen.

**Comment by Th3Dilli** [comment]
Pls close because it is not BP related bug @ST6Daniel
