### ISSUE TITLE
Upon launching mod this error appears

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#21]
No entry 'bin\config.bin/CfgWeapons/ItemInfo.scope'.

**Comment by MorphineBP** [comment]
Got it too sometimes. A3 related, harmless.

**Comment by ST6Daniel** [comment]
Harmless but annoying, we can only hope for better A3 mod-support...

**Comment by Th3Dilli** [comment]
@ST6Daniel pls close issue
