### ISSUE TITLE
Errors on first time spawn

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#22]
Cannot load texture ca\weapons_e\data\default_ti_ca.paa.

No entry 'bin\config.bin/CfgWeapons.'.

**Comment by MorphineBP** [comment]
Arma 3 bug ? A classic one, harmless.

**Comment by ST6Daniel** [comment]
Hm, hope the ArmA3 mod-support will improve until 2018.

**Comment by MorphineBP** [comment]
Like us all. You can delete.

**Comment by Th3Dilli** [comment]
close issue pls @ST6Daniel
