### ISSUE TITLE
Most of the times loot in toilets inaccessible

### ISSUE THREAD

**Issue by D4n2021** [deathlyrage/breakingpointmod#23]
When opening wooden door of toilet, in most cases no "inventory" menu available. Collision bug

**Comment by MorphineBP** [comment]
True, but Arma 3 related and quite harmless since toiles are not interesting to loot (low tier).

**Comment by ST6Daniel** [comment]
Then why not remove all toilet things to not freak out new BP players?

**Comment by MorphineBP** [comment]
My point is, if you begin to list all similar minor bugs like this one... it will be endless. I've got tons of it in mind. Chernarus is full of it. For now it's not relevant. Stay focus on important stuff. Don't worry about optimization...
