### ISSUE TITLE
Enhancement idea - new state: player critically wounded first when getting shot instead of instant dieing

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#24]
So to add a Revive script so that player could still crawl into cover and get revived by a teammate. And headshots insta-death.

**Comment by MorphineBP** [comment]
Go play PUBG. Jesus... No no no...

**Comment by ST6Daniel** [comment]
PUBG? Revive is a normal ArmA 3 feature...

**Comment by MorphineBP** [comment]
Use the discord for this, keep the debug area clean. BP was and is hardcore, people will confirm it to you. This is not a place for debate here.
