### ISSUE TITLE
Item "plate" never spawning in loot objects?

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#25]
Never ever seen plate before, but it's mentioned in the wiki?

**Comment by MorphineBP** [comment]
Dude STOP posting shit on this github !!
Post only **verified and reproduced bugs**, not your noobs assumptions. It's not a discussion !
You're not 100% sure ? don't post !

**Comment by ST6Daniel** [comment]
With your attitude were not gonna get far in fixing bugs... you realize? Ofc. this ISN'T high priority, but do I have the possibility of adding "low priority" tag in this post? NOOO...

**Comment by MorphineBP** [comment]
Are you kidding ? It's with your childish shit that bugs can't be targeted properly. You're confusing everything, posting BS everywhere.
Spam in discord if you want (like you're already do) but at least keep this place clean and delete your shit (this topic is 100% useless).
You can't find an item, so it's a bug ?? Are you stupid or what. Reading an outdated wiki will not give you any experience.  Play a LOT and come back after.

**Comment by ST6Daniel** [comment]
Ok then I'm surprised there's a plate in the wiki when I've never seen a single one in my 3 years of playing BP... Why was it removed? Or if not, then it IS a bug. (I've looted way more than 1000 items already and NEVER saw it)

**Comment by MorphineBP** [comment]
2 wrong assumptions again :
* the wiki is not perfectly updated, so the wiki is not 100% reliable.
* The "Plate Carrier Plus" is ingame, I've found one yesterday again (smoking crate). the fact you can't find it in 3 years in not relevant. Talk about it around you and you'll find people with this thing everywhere.
You can delete.

**Comment by ST6Daniel** [comment]
Not plate carrier, just "plate" (the thing you eat from)

**Comment by Th3Dilli** [comment]
Pls close issue .... @ST6Daniel

**Comment by ST6Daniel** [comment]
But there really NEVER is a plate in a loot box for my... Fix it please or remove it for once and for all

**Comment by Th3Dilli** [comment]
that thing you are talking about is a trash item do u want more trash items?

**Comment by ST6Daniel** [comment]
It is a trash item that iirc I saw in the mod files, so it's a little shame it's currently not spawning in when players downloaded the model/texture... Not more trash, just this one plate to spawn finally (never ever spawned for me). Not sure atm what the exact file name is but it contains the word "plate".

**Comment by Th3Dilli** [comment]
it is not intended to spawn at all, if you would like to have it in agme then update the loot tabele so it will spawn otherwise leave it how it is and close the issue

**Comment by ST6Daniel** [comment]
Maybe it was a Dev typo in loot table so not spawning? Or why not? Is it throwable item that can kill zombies? Then I would update loot table.

**Comment by Th3Dilli** [comment]
yeah sure update the loot table, but still not an major issue pls remove

**Comment by ST6Daniel** [comment]
So do I fork or pull request? (never done this before)

**Comment by ST6Daniel** [comment]
Nvm sb. removed the beautiful plate already from the loot table some weeks ago it seems. sad...
