### ISSUE TITLE
player statistics saved anywhere?

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#26]
Since launcher is inoperational, are points even saved currently? Can they be displayed anywhere?

**Comment by MorphineBP** [comment]
No ! It's not a bug, it's a temporary removed feature. Don't post it here.
Points are fine, just not accessibles.

**Comment by ST6Daniel** [comment]
Good, can't wait to see the score I currrently have :) (assuming the stats got wiped few months ago and now are saved and sometime within the next weeks/months will be available to see)

**Comment by MorphineBP** [comment]
Each server got his own DB (DataBase). Points are saved there and currently not visible.
You can delete.
Use the discord for things like this you want to talk about, not this place.

**Comment by Th3Dilli** [comment]
Fixed pls close issue @ST6Daniel
