### ISSUE TITLE
Breaking Point Launcher ?

### ISSUE THREAD

**Issue by cshard447** [deathlyrage/breakingpointmod#3]
will there be access to the source code of the launcher?

**Comment by skiperh1n1** [comment]
We just dont have servers files, its now needed bigest. Launcher will be write on C# very easy

**Comment by deathlyrage** [comment]
I can give source code to the launcher, but I don't know how necessary it will be.

**Comment by cshard447** [comment]
I need a launcher for the proper operation of the legions and the continued development of the modification

**Comment by cshard447** [comment]
here is my skype: andfox447
here is my email: andorex9999@gmail.com

**Comment by cshard447** [comment]
and at the same time I wanted to preserve your authorship ;)
