### ISSUE TITLE
Make breakingpoint_server_config optional?

### ISSUE THREAD

**Issue by deathlyrage** [deathlyrage/breakingpointmod#37]
Is it possible to have the default server config defined in breakingpoint_server and server owners only need to include a breakingpoint_server_config pbo if they are overriding config. 

This way I don't have to include a pre-built pbo in steam and end up overwriting a existing config pbo every server update.

@Th3Dilli

**Comment by RevolutionServidores** [comment]
Good evening,

First of all, congratulations on the project.

I have a question about today's update, should this new folder be placed in which place?

Thank you

**Comment by Th3Dilli** [comment]
I updated the readmy so you should be ready to get it going @RevolutionServidores 
check out the pull request until deathly does a merge

**Comment by Th3Dilli** [comment]
done @deathlyrage
