### ISSUE TITLE
Haven bug : Fuel Barrel content is not persistent 

### ISSUE THREAD

**Issue by MorphineBP** [deathlyrage/breakingpointmod#45]
Haven's specific item "Fuel Barrel" is not working properly.
You can stock fuel inside (refuel option), you can take it back later (siphon) but after a restart : the item is always empty. If fuel inside disappears at restart, the item has no purpose.

http://aragones.info/BPWIKI/BP%20Wiki/BPU%20Wiki/thezombieinfection.com/wiki/index19ed.html?title=Haven

http://steamcommunity.com/id/MorphineBP/screenshot/875246541770645512

**Comment by Th3Dilli** [comment]
i checkt that one but could not figure out what is wrong exactly but as far i found out i dont get any value from server on setup so maybe somthing with the extension

**Comment by KamikazeXeX** [comment]
@Th3Dilli, you are correct, I just checked the hive extension source and the query string doesn't grab the stored fuel value, I'll see if I can implement this at some point.

**Comment by KamikazeXeX** [comment]
Fixed in #74 ;)

**Comment by MorphineBP** [comment]
Tks ! Closing.
