### ISSUE TITLE
Adapting to allow breaking point to be hosted on game hosts servers, not just dedicated servers. 

### ISSUE THREAD

**Issue by McBeardy296** [deathlyrage/breakingpointmod#47]
Is there a way that the mod can be adjusted to allow it to be hosted on a game server host (such as GTX, villayer, and so on)?

I have been attempting to do this myself, but I’m hoping that others might be able to contribute?   I am also trying to remove the restart/shutdown timer in order to allow the hosts scripts to be able to control this, and also to bring night play into the game (possibly with fast nights?)

**Comment by deathlyrage** [comment]
You will have to contact the hosts and ask for integration with their systems.
