### ISSUE TITLE
How to remove the auto restarting of servers

### ISSUE THREAD

**Issue by RespawnGaming** [deathlyrage/breakingpointmod#48]
can anyone tell me how i can disable the auto restarting for the servers. As it enters shutdown mode and i have to close the servers and reopen them. Any help would be good. thank you

**Comment by Overdese** [comment]
Restart of servers is necessary. Why do you want disable it?

**Comment by RespawnGaming** [comment]
i will use something else. like bec or something. when the servers enter shutdown mode you cant stop it or stop it from spamming

**Comment by RespawnGaming** [comment]
so no one knows ?

**Comment by tinboye** [comment]
im kind of in the same boat, except with my server. it says its going into shut down mode, but its not 3 hrs later, it will happen within 30 min or less of starting up the server.

**Comment by MorphineBP** [comment]
It has been discussed already : for auto-restart use FireDaemon. It's already coded, you have nothing to do, except creating a process. It will stop and restart all your servers perfectly.
Search "Firedaemon" in the BP discord history.

**Comment by Th3Dilli** [comment]
as far as i know it is in the extension hardcoded so you can not change when it will restart, but u can use windows task sheduler to execute a .bat that kills the server (bec is out of support if i am right)
