### ISSUE TITLE
Way to change Zombies behaviour?

### ISSUE THREAD

**Issue by RespawnGaming** [deathlyrage/breakingpointmod#49]
In other words make them walk, other then run. thank you

**Comment by MorphineBP** [comment]
Develop more if you expect any interest on your.... "request".
Zombies are not perfect (collision bug, invisible inside some buildings, aggro quite basic) but slowing them down is kinda ridiculous. They're too easy atm, not the opposite. Ask around you to confirm this.

**Comment by RespawnGaming** [comment]
Im just toying around on a private server. who dont just enjoy killing slow zombies lool :)

**Comment by deathlyrage** [comment]
This is for reporting issues and project development, not asking for help on how to do things on your private server. You need to figure it out for yourself.
