### ISSUE TITLE
Can't find the serverkey

### ISSUE THREAD

**Issue by kakelakel** [deathlyrage/breakingpointmod#5]
Not sure if i'm missing something here but i'm having trouble finding the key for @BreakingPoint.. Any pointers on how to proceed?

Looking forward to play Breakingpoint once again :)

**Comment by deathlyrage** [comment]
Going to add it now, thanks for reporting.

**Comment by deathlyrage** [comment]
I'm still downloading the repo again so i can add the server key, but if you need it right now, here is a copy:
https://cdn.discordapp.com/attachments/358390236012609550/358475629181796355/deathlyrage.bikey

**Comment by deathlyrage** [comment]
Fixed + Closing
