### ISSUE TITLE
2 links in steam mod discussions still leading to offline website.

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#52]
2 announcements of Deathly still pointing to thezombieinfection.com.

**Comment by MorphineBP** [comment]
Specify which announcements and which links. Don't just send stuff like that, without details.

**Comment by ST6Daniel** [comment]
the 2 links in the 2 bottom pinned announcements: https://steamcommunity.com/sharedfiles/filedetails/discussions/426629791

**Comment by MorphineBP** [comment]
Legit, it would not hurt to remove or update those pinned threads.

**Comment by deathlyrage** [comment]
Fixed
