### ISSUE TITLE
Allow enabled state DS houses/CUP terrains for Altis

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#54]
Cause when currently activated, players cannot join Altis server

**Comment by MorphineBP** [comment]
Be specific. You're talking about TFS servers, they have a Chernarus servers where those 2 mods are required.
When the map does not need other mods, no need to add them oc. There is already enough bugs/issues.
You can close.

**Comment by deathlyrage** [comment]
This is a server issue and not a mod issue. Won't Fix.
