### ISSUE TITLE
Weapon on single fire mod always when switching from Katana

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#55]
Happening on AK 107. It should either remember last firing mode or always be full auto. (whatever is easier to script)

**Comment by MorphineBP** [comment]
Same for all weapons. Pretty sure it's arma sided.

**Comment by deathlyrage** [comment]
Bug with arma, not fixable easily.

**Comment by ST6Daniel** [comment]
ok reported it to feedback bistudio.
