### ISSUE TITLE
Not able to "gut" sheep anymore after killing them

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#57]
So I am independent, has sth. changed in a patch?

**Comment by ST6Daniel** [comment]
same with chicken

**Comment by MorphineBP** [comment]
You simply don't have a knife on you. The faction does not matters.
Send a video to support your "bugs"', you're doing too much wrong reports.

**Comment by Th3Dilli** [comment]
i hoped to see the issue tracker not spammed with bullshit after i sorted some things out with you today but you keep spamming shity bug reports and use this section like a chat so i am not gona bother with you anymore and ignore your stuff ...
