### ISSUE TITLE
[minor suggestion] slight starter engine probability increase on Altis

### ISSUE THREAD

**Issue by ST6Daniel** [deathlyrage/breakingpointmod#58]
So as we can see in this file: https://github.com/deathlyrage/breakingpointmod/blob/master/ModSource/breakingpoint_code/Configs/CfgLoot/CfgObjectLoot.hpp

the probability is only 5%. I searched more than 10 factories on Altis, found sth. like 5 worn tires but not a single Starter Engine. My suggestion, increase to 7% (as worn tire is).

**Comment by ST6Daniel** [comment]
(happened around Pyrgos and Charkia)

**Comment by deathlyrage** [comment]
This could be a bug with the loot spawn system and not a % chance thing. Can't take this suggestion based upon this alone sorry.
