### ISSUE TITLE
enemy dies only after 5 chest shots with 7.62mm (standard)

### ISSUE THREAD

**Issue by sLy1337** [deathlyrage/breakingpointmod#71]
hi
it appears like the 7.62mm (standard) weapons do a lot less damage.
we had several situations where we shot someone in the chest 4-5 times before he died.
we know of course, that 7.62mm is not a oneshot kill, but 5 chest seems a bit weak.
an admin of a community server told me that an arma update maybe changed the damage values for 7.62mm and this needs to be adressed directly at the breaking point devs.

is it possible  to adress the issue in one of the next patches?

thank you and greetings.

**Comment by MorphineBP** [comment]
To complete the report : http://aragones.info/BPWIKI/BP%20Wiki/BPU%20Wiki/thezombieinfection.com/wiki/index9c3b.html?title=Damage
The occasional bug area (between torso HP) does not explain the frequent inefficiency of 7.62 ammo.

**Comment by DonniePlays** [comment]
There are several reasons why a specific weapon would be inconsistent when hitting a target. Rangers have natural body armor in game that is stronger with each level. Also different vests have different levels of armor as well. Also where you hit a player makes a difference in how much damage is done. Also the weapon and ammo specific type plays a role in bleeding. You also have to consider medical. Players can do surgery on each other and that saves death a lot of times. Also level 3 Rangers can stop bleeding by using their medic backpack.

**Comment by DonniePlays** [comment]
Damage armor system was improved in the last update with vests.
