### ISSUE TITLE
Zombies looks bad 

### ISSUE THREAD

**Issue by sony77** [deathlyrage/breakingpointmod#72]
Warning Message: Embedded skeleton OFP2_ManSkeleton in 'a3\characters_f_bootcamp\common\vr_soldier_f.p3d' has different [ bone name ] in different p3d files. Skeleton/model 'breakingpoint_classes\models\bp_hunter2.p3d' will probably not work correctly.
18:14:32 Error: Skeleton of the head a3\characters_f\heads\m_white_01.p3d doesn't match the skeleton of the corresponding body breakingpoint_classes\models\bp_hunter2.p3d
18:14:32 Error: Skeleton of some head doesn't match the skeleton of the corresponding body

**Comment by KamikazeXeX** [comment]
Related to my fix in #73 awaiting the pull request being accepted and a update pushed to the workshop.

**Comment by sony77** [comment]
Changed the full ModSource Folder on the Server but it has no effect the Zeds looks like running Trees.

**Comment by KamikazeXeX** [comment]
@sony77 This change has to be made by @deathlyrage and then pushed out to the workshop, it's not a server-side only fix.

**Comment by MorphineBP** [comment]
Solved by the last update. To be closed.
