### ISSUE TITLE
Faction Stats bug when manually opening

### ISSUE THREAD

**Issue by Ghosttownn** [deathlyrage/breakingpointmod#79]
So I have did a fresh install of the BP mod several times & each is still coming back with this issue.

When first logging into the server you see the Factions Stats which is showing correctly:
![first login](https://user-images.githubusercontent.com/34558377/34021222-9c3dc792-e106-11e7-886e-559e3609cdec.png)

After getting ingame and opening up the Faction Stats manually by using the custom user key 12, It bugs out and looks like this:
![manually opening](https://user-images.githubusercontent.com/34558377/34021256-c0a720c4-e106-11e7-9f7e-fb3cef5d4e45.png)

I have two monitors so I apologize on the double images.

**Comment by MorphineBP** [comment]
Fake issue. The user doesn't understand than the first screen is not the Faction Stats but the temporary spawning screen, displaying factions people on map + location, not the stats.
The second screen is the recently added Factions Stats screen (user CK 12), and has been obviously designed to look like the other screen.... 
Can be closed.

**Comment by Ghosttownn** [comment]
Was not a fake issue, was a misunderstanding that was already sorted in Discord.

I have no idea how to close/delete the issue and it's why it was left open.

**Comment by MorphineBP** [comment]
Just click on close issue lol.
