### ISSUE TITLE
Debug console commands don't work?

### ISSUE THREAD

**Issue by gianni001** [deathlyrage/breakingpointmod#85]
Hosting a local server to do some testing but commands in the debug console don't seem to fire.

Tried adjusting cfgRemoteExec in description.ext but nothing seems to matter.

Is it blocked elsewhere?

Thanks!

**Comment by DonniePlays** [comment]
In breakingpoint_code, the mission files have this parameter set:
enableDebugConsole = 0;

It is blocked for us in the mod.
