### ISSUE TITLE
Scripterrors

### ISSUE THREAD

**Issue by sony77** [deathlyrage/breakingpointmod#87]
Have we any Chance to disable the Scripterrors on Server?
-hideScriptErrors and -hideOnScreenErrors not work in the start.bat

**Comment by sony77** [comment]
![20180220_114200](https://user-images.githubusercontent.com/26782880/36665673-7da8dd96-1ae8-11e8-8d9f-70794cc01a54.jpg)
![20180220_120610](https://user-images.githubusercontent.com/26782880/36665674-7dc5d8d8-1ae8-11e8-9a39-2d0a9d1f6fde.jpg)
![20180220_123729](https://user-images.githubusercontent.com/26782880/36665675-7e0894a2-1ae8-11e8-83df-14bff0195f7d.jpg)
![20180220_150848](https://user-images.githubusercontent.com/26782880/36665676-7e4d7d9c-1ae8-11e8-8e8f-89384b1db8bd.jpg)

That Picture boden not found appears when first Time open Inventory!

**Comment by ST6Daniel** [comment]
He wrote "arma 3 issue" few months ago to me, guess it'll be same reply here (Bohemia's modsupport=terrible when it comes to errors)

**Comment by DonniePlays** [comment]
This has been fixed in the last mod update.
