### ISSUE TITLE
Progression is not working

### ISSUE THREAD

**Issue by FallAngelpl** [deathlyrage/breakingpointmod#89]
Greetings
Quick question - we was start play on BOP servers (cherno and Malden) and on both servers stats/points are not counting.
0 km, 0 zombies, 0 bandits 
Any problems from server/modpack site or we have not valid hmm accounts/version?
We was check and all of us 4 players have this same issue (survivalist, traper)

Thank you for any help

**Comment by tinboye** [comment]
Zombie kills show for me per session. But there doesn't appear to be any point system in place that I can tell. If you go into custom controls. Set key for stats. I think it's 12.  I set mine for insert key. Then it shows how many zeds you killed during that session

**Comment by DonniePlays** [comment]
The progression is working. The stats you see on the diary are only for the in game session. The database does record all zombie and player kills. Your server owner should be able to track and post the stats for you.
